spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: true
  thymeleaf:
    cache: false
## Mybatis
mybatis:
    typeAliasesPackage: com.tao.domain
    mapperLocations: classpath:mapper/*.xml
server:
  port: 8080
  context-path: /letou
logging:
  file: ./log/luck.log
#  level:
#        com.tao: debug
---
## 数据库
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123qwe
        driver-class-name: com.mysql.jdbc.Driver
        dbcp2:
          initial-size: 10
          max-active: 20
    profiles: dev
    redis:
      host: localhost
      port: 6379
---
## 数据库
spring:
    datasource:
        url: jdbc:mysql://172.17.0.2:3306/letou?useUnicode=true&characterEncoding=utf-8
        username: topic_dev
        password: Os3bayQe
        driver-class-name: com.mysql.jdbc.Driver
    profiles: prod
    redis:
          host: 172.17.0.1
          port: 6379
