## 数据库
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123qwe
        driver-class-name: com.mysql.jdbc.Driver

## Mybatis
mybatis:
    typeAliasesPackage: com.tao.domain
    mapperLocations: classpath:mapper/*.xml