package com.tao.mapper;


import com.tao.domain.LogFeedback;

import java.util.List;

public interface LogFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_feedback
     *
     * @mbggenerated Fri Feb 23 21:16:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_feedback
     *
     * @mbggenerated Fri Feb 23 21:16:17 CST 2018
     */
    int insert(LogFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_feedback
     *
     * @mbggenerated Fri Feb 23 21:16:17 CST 2018
     */
    int insertSelective(LogFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_feedback
     *
     * @mbggenerated Fri Feb 23 21:16:17 CST 2018
     */
    LogFeedback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_feedback
     *
     * @mbggenerated Fri Feb 23 21:16:17 CST 2018
     */
    int updateByPrimaryKeySelective(LogFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_feedback
     *
     * @mbggenerated Fri Feb 23 21:16:17 CST 2018
     */
    int updateByPrimaryKey(LogFeedback record);

    List<LogFeedback> getList(LogFeedback LogFeedback);

    List<LogFeedback> getListDesc();
}