package com.tao.mapper;

import com.tao.domain.LetouLog;
import com.tao.domain.Whole;
import org.apache.ibatis.annotations.Param;

public interface WholeMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letou_log
     *
     * @mbggenerated Mon Jan 08 13:51:28 CST 2018
     */
    int insert(Whole record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letou_log
     *
     * @mbggenerated Mon Jan 08 13:51:28 CST 2018
     */
    Whole selectByPrimaryKey(@Param("id") Long id,@Param("mod")Integer mod);


    /**
     * 增加中奖数 +1
     */
     void increase(Whole wholeAdd);

    /**
     * 更正数据
     * @param wholeAdd
     */
    void fixed(Whole wholeAdd);

    /**
     * 查询号码历史表现情况
     * @param whole
     * @return
     */
    Whole getBySelect(Whole whole);
}