package com.tao.mapper;

import com.tao.domain.LetouLog;
import com.tao.domain.Whole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WholeMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letou_log
     *
     * @mbggenerated Mon Jan 08 13:51:28 CST 2018
     */
    int insert(Whole record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letou_log
     *
     * @mbggenerated Mon Jan 08 13:51:28 CST 2018
     */
    LetouLog selectByPrimaryKey(@Param("id") Long id,@Param("mod")Integer mod);


}